# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
 config.vm.box = "hashicorp/precise32"
 config.vm.network "private_network", ip: "192.168.33.10"
 config.vm.synced_folder "../", "/var/www/arcavias-demo", type: "nfs"
 config.vm.provision "shell", path: "Vagrant.setup"
end
