<?php

/**
 * @copyright Copyright (c) Metaways Infosystems GmbH, 2013
 * @license LGPLv3, http://www.arcavias.com/en/license
 */

try
{
	echo ( isset( $this->history ) ? $this->history->getBody() : '' );
	echo ( isset( $this->favorite ) ? $this->favorite->getBody() : '' );
	echo ( isset( $this->watch ) ? $this->watch->getBody() : '' );
}
catch( MW_Exception $e )
{
	echo 'An error occured';
}
catch( Exception $e )
{
	echo 'Error: ' . $e->getMessage();
}
?>
