<?php

/**
 * @copyright Copyright (c) Metaways Infosystems GmbH, 2013
 * @license LGPLv3, http://www.arcavias.com/en/license
 */

try
{
	echo ( isset( $this->client ) ? $this->client->getHeader() : '' );
	echo ( isset( $this->client ) ? $this->client->getBody() : '' );
}
catch( MW_Exception $e )
{
	header( 'HTTP/1.1 500 Database error' );
}
catch( Exception $e )
{
	header( 'HTTP/1.1 500 ' . $e->getMessage() );
}
?>