<?php

/**
 * Error document 404
 */

header("HTTP/1.0 404 Not Found");
global $e;
?>
<html>
<head>
	<title>404 Not Found</title>
	<link rel="stylesheet" href="styles/main.css" />
</head>
<body>
	<h1>Oops...</h1>
	<hr />
	<p>The page you are trying to access does not exist or perhaps it was removed.</p>
	<div style="overflow: visible; margin-top: 10px; padding: 2px; border: 1px dashed black;color:red;">
		<strong>Debugging information:</strong><br />
		<p><?php echo $e->getMessage(); ?></p>
		<pre><?php echo $e->getTraceAsString(); ?></pre>
	</div>
</body>
</html>