<?php

/**
 * Error document 404
 */

header("HTTP/1.0 500 Internal Server Error");
global $e;
?>
<html>
<head>
	<title>Internal server error</title>
	<link rel="stylesheet" href="styles/main.css" />
</head>
<body>
	<h1>Internal server error</h1>
	<hr />
	<p>Application has encountered some internal error.</p>
	<p>Please make sure you've executed <strong>phing install</strong> on the command line</p>
	<div style="overflow: visible; margin-top: 10px; padding: 2px; border: 1px dashed black;color:red;">
		<p><?php echo $e->getMessage(); ?></p>
		<pre><?php echo $e->getTraceAsString(); ?></pre>
	</div>
</body>
</html>